const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
const FETCH_MOVIES = 'FETCH_MOVIES';

const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST';
const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE';

const FETCH_VIDEO_KEY_REQUEST = 'FETCH_VIDEO_KEY_REQUEST';
const FETCH_VIDEO_KEY_SUCCESS = 'FETCH_VIDEO_KEY_SUCCESS';
const FETCH_VIDEO_KEY_FAILURE = 'FETCH_VIDEO_KEY_FAILURE';

const CHANGE_FILTER = 'CHANGE_FILTER';

export {
  FETCH_MOVIES_REQUEST, FETCH_MOVIES_SUCCESS, FETCH_MOVIES_FAILURE,
  FETCH_GENRES_REQUEST, FETCH_GENRES_SUCCESS, FETCH_GENRES_FAILURE,
  FETCH_VIDEO_KEY_REQUEST, FETCH_VIDEO_KEY_SUCCESS, FETCH_VIDEO_KEY_FAILURE,
  CHANGE_FILTER,
  FETCH_MOVIES,
};
